I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1638, in script
    ar "We have to get everyone out! We have no idea how large this explosive might be."
IOError: Couldn't find file 'sounds/VO/uard_Sound_the_Alarm.ogg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1638, in script
    ar "We have to get everyone out! We have no idea how large this explosive might be."
  File "/Applications/renpy-6.99.6-sdk/renpy/ast.py", line 594, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "/Applications/renpy-6.99.6-sdk/renpy/exports.py", line 1032, in say
    who(what, interact=interact)
  File "/Applications/renpy-6.99.6-sdk/renpy/character.py", line 826, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "/Applications/renpy-6.99.6-sdk/renpy/character.py", line 688, in do_display
    **display_args)
  File "/Applications/renpy-6.99.6-sdk/renpy/character.py", line 491, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/Applications/renpy-6.99.6-sdk/renpy/ui.py", line 277, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/renpy-6.99.6-sdk/renpy/display/core.py", line 2346, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "/Applications/renpy-6.99.6-sdk/renpy/display/core.py", line 2633, in interact_core
    renpy.audio.audio.interact()
  File "/Applications/renpy-6.99.6-sdk/renpy/audio/audio.py", line 790, in interact
    periodic()
  File "/Applications/renpy-6.99.6-sdk/renpy/audio/audio.py", line 724, in periodic
    c.periodic()
  File "/Applications/renpy-6.99.6-sdk/renpy/audio/audio.py", line 340, in periodic
    topf = load(self.file_prefix + topq.filename + self.file_suffix)
  File "/Applications/renpy-6.99.6-sdk/renpy/audio/audio.py", line 74, in load
    rv = renpy.loader.load(fn)
  File "/Applications/renpy-6.99.6-sdk/renpy/loader.py", line 517, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'sounds/VO/uard_Sound_the_Alarm.ogg'.

Darwin-14.5.0-x86_64-i386-64bit
Ren'Py 6.99.6.739
Angelica Victorian Detective 0.2
